### ISSUE TITLE
The library does not support the Arabic language

### ISSUE THREAD

**Issue by s2yed** [kechankrisna/flutter_esc_printer#2]
: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument (string): Contains invalid characters.: "بسم الله الرحمن الرحيم"
[        ] E/flutter (10959): #0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:89:9)
[        ] E/flutter (10959): #1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
[        ] E/flutter (10959): #2      Ticket._encode (package:esc_pos_utils/src/ticket.dart:67:21)

**Comment by s2yed** [comment]
To avoid the problem, I downloaded the library and used it
   Uint8List encoded =
         await CharsetConverter.encode ('ISO-8859-6', 'Tax invoice'); //

Add this line

  List <int> bytesReversed = [];

     for (int bytes in textBytes.reversed) {
        bytesReversed.add (bytes);
     }

In _text

Because the letters were showing me inverted form

**Comment by s2yed** [comment]
The library does not support the Arabic language

I need some update before you because there is a problem in the Arabic language. The letters of the language appear inverted
This is the print image

 
![WhatsApp Image 2021-03-11 at 11 12 09 AM](https://user-images.githubusercontent.com/52221297/110763838-fab89380-825a-11eb-9841-381cb7edfcb3.jpeg)

This is the code used


  Uint8List encoded =
    await CharsetConverter.encode('ISO-8859-6', "فاتورة ضريبة   فاتورة ضريبة فاتورة ضريبة"); //
    // var  decoded = await CharsetConverter.decode(
    //       "ISO-8859-6",encoded); windows-1256

    // print(decoded);
    ticket.textEncoded(encoded,
        styles: PosStyles(align: PosAlign.right,width: PosTextSize.size1  ),maxCharsPerLine: 30,linesAfter: 1  );

    Uint8List encoded2 =
    await CharsetConverter.encode('ISO-8859-6', 'مابيقرا شي وهو بيستخدم');

    ticket.textEncoded(encoded2,
        styles: PosStyles(align: PosAlign.center,width: PosTextSize.size1, bold: true) );

    ticket.textEncoded(encoded2,
        styles: PosStyles(align: PosAlign.right,width: PosTextSize.size1 ) );


![WhatsApp Image 2021-03-11 at 11 12 33 AM](https://user-images.githubusercontent.com/52221297/110763966-23d92400-825b-11eb-949d-fbf8e27b6a65.jpeg)


I made some modification in Ticket part
Inside_text, this modification reverses the letters and appears in a nice way, but in some of the characters they are separated from each other
Like this picture

ist <int> bytesReversed = [];
 

     for (int bytes in textBytes.reversed) {
       bytesReversed.add (bytes);
     }
 
     bytes + = bytesReversed;



![WhatsApp Image 2021-03-11 at 11 20 27 AM](https://user-images.githubusercontent.com/52221297/110764500-cf827400-825b-11eb-9bd2-ee51c03cb8c2.jpeg)



Normal shape for text like this (فاتورة ضريبة)




There is also a problem printing photos on an  ( intermec )bluetooth printer.
But it works on its ( Rress  )  printer
![WhatsApp Image 2021-03-10 at 6 26 23 PM](https://user-images.githubusercontent.com/52221297/110765031-6c451180-825c-11eb-8e54-3573e77196e4.jpeg)


How is this problem solved?

**Comment by blackangiliq** [comment]
u can use this 

you can check this 

this repo use 3 laiblary 

secreenshot to convert widget to image 
and image library to convert it to uint8 
and pos_print to print it ass u love to show 

                     


 https://github.com/blackangiliq/flutter_pos_printer_spport_arabic
